# Generated by Django 2.2.8 on 2020-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Feature_Description', models.TextField(blank=True, null=True)),
                ('Feature_Image', models.ImageField(blank=True, max_length=10000, null=True, upload_to='features/')),
            ],
        ),
    ]
