# Generated by Django 2.2.8 on 2020-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason_Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Reason_Description', models.TextField(blank=True, null=True)),
                ('Reason_Image', models.ImageField(blank=True, max_length=10000, null=True, upload_to='features/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
