# Generated by Django 2.2.8 on 2020-07-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0002_auto_20200706_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Sub_Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Feature_Sub_Description', models.TextField(blank=True, null=True)),
                ('Feature_Sub_Image', models.ImageField(blank=True, max_length=10000, null=True, upload_to='features/')),
                ('Feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamasterapp.Feature')),
            ],
        ),
    ]
