# Generated by Django 2.2.8 on 2020-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0004_auto_20200706_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfeature',
            name='Feature_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='Feature_Image',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='features/'),
        ),
    ]
