# Generated by Django 2.2.8 on 2020-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0005_auto_20200706_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfeature',
            name='Feature_Sub_Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
