# Generated by Django 2.2.8 on 2020-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0007_auto_20200706_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='Name', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='email@example.com', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
