# Generated by Django 2.2.8 on 2020-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=130, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
                ('phone', models.CharField(blank=True, max_length=130, null=True)),
                ('email_address', models.EmailField(max_length=120)),
                ('facebook_url', models.URLField(blank=True, max_length=130, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=130, null=True)),
                ('footer', models.CharField(blank=True, max_length=130, null=True)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
