# Generated by Django 2.2.8 on 2020-07-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0009_companydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, default='Name', max_length=100, null=True),
        ),
    ]
