# Generated by Django 2.2.8 on 2020-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0010_feedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('slider_name', models.CharField(blank=True, default='slider', max_length=100, null=True)),
                ('slider_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='sliders/')),
                ('slider_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
