# Generated by Django 2.2.8 on 2020-07-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0012_slider_slider_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
