# Generated by Django 2.2.8 on 2020-07-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamasterapp', '0014_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_name',
        ),
    ]
